#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "Usage: newscript [-d] filename"
    echo "-d     deletes the file"
    exit 0
fi

SCRIPTPATH="$HOME/.local/bin"

[ ! -d "$SCRIPTPATH" ] && mkdir -p "$SCRIPTPATH"

if [ "$1" = "-d" ]; then
  [ -f "$SCRIPTPATH/$2" ] && rm "$SCRIPTPATH/$2"
  exit 0
fi

SCRIPT="$SCRIPTPATH/$1"

if [ ! -f "$SCRIPT" ]; then
  echo "#!/bin/bash" > "$SCRIPT"
  chmod +x "$SCRIPT"
fi

code "$SCRIPT"
